### ISSUE TITLE
The tracking result is very poor

### ISSUE THREAD

**Issue by yantingxin-0** [wangxiyang2022/DeepFusionMOT#10]
2 10286 Car 0 0 -0.105700 406.157410 156.116806 472.713715 179.827499 1.480040 1.621534 4.009197 -10.703653 -0.045948 45.642753 -0.337726 0.380400
19 10334 Car 0 0 -1.251100 479.489685 148.728104 535.187012 180.391800 1.472786 1.591026 3.703640 -4.828685 -0.000625 35.240201 -1.448429 0.263900
19 10336 Car 0 0 -1.502300 536.317688 148.683197 576.778625 182.403107 1.469094 1.601246 3.936529 -2.167853 0.080312 32.730272 -1.593040 1.457500
30 10354 Car 0 0 -0.164000 451.118103 149.604904 527.529724 176.887100 1.493714 1.644311 4.124940 -6.632768 -0.215943 40.524087 -0.332871 0.700600
43 10382 Car 0 0 1.532400 548.516113 151.523895 579.900391 179.494507 1.475554 1.589863 3.922437 -2.424710 -0.039133 39.222688 1.749560 0.627200
52 10398 Car 0 0 1.594700 503.373810 149.072006 531.887817 175.644897 1.466403 1.579160 3.717383 -5.139709 -0.283145 41.671964 1.466257 2.203200
53 10406 Car 0 0 3.195600 0.000000 132.323593 30.420601 197.434799 1.510457 1.619089 4.120591 -17.704147 0.372574 18.385816 2.508452 1.476600
58 10420 Car 0 0 -1.436800 525.856384 148.578705 564.621521 177.841797 1.501063 1.609314 3.879169 -3.225207 -0.163217 38.520432 -1.529120 -0.294400
65 10434 Car 0 0 2.152000 50.473598 149.702499 143.962006 184.047699 1.465226 1.592391 3.809577 -22.885414 0.149142 31.758262 1.582609 -0.082200
66 10436 Car 0 0 -0.117600 407.196289 155.613907 474.521790 179.408203 1.481429 1.628926 4.053589 -10.627517 -0.070049 45.657759 -0.344503 0.634600
77 10454 Car 0 0 -1.479800 470.531189 149.177307 509.474213 179.504105 1.477669 1.629666 4.060663 -5.863790 -0.055531 36.744823 -1.594874 0.021000
110 10518 Car 0 0 -2.070600 504.069305 151.456299 573.159973 185.281296 1.462009 1.588797 3.731426 -3.174303 0.201311 32.295368 -2.466767 -0.297500
115 10526 Car 0 0 2.120400 136.547607 142.091202 242.736099 184.908707 1.493889 1.617637 4.065674 -15.640128 0.163692 26.487802 2.000112 -0.633100
122 10542 Car 0 0 0.273500 5.581300 138.283600 192.050995 195.136200 1.494729 1.605843 4.045877 -14.154694 0.394258 19.956930 -0.439366 1.520100

This is the tracking result of the 0000 sequence, why is the result so bad?

**Comment by yantingxin-0** [comment]
The file needs to be sorted

**Comment by yuanfuture** [comment]
Which files need to be sorted? Thank you

**Comment by yantingxin-0** [comment]
> Which files need to be sorted? Thank you


All loaded files are not loaded in order, so they need to be sorted

**Comment by yuanfuture** [comment]
Thank you very much, but after sorting again, I found that there were still many detection boxes in the output result that were not in the correct position. Why did this happen? I sorted the 3D dataset, 2D dataset, calib dataset, and image_02 dataset. Did I miss anything?

**Comment by yantingxin-0** [comment]
> Thank you very much, but after sorting again, I found that there were still many detection boxes in the output result that were not in the correct position. Why did this happen? I sorted the 3D dataset, 2D dataset, calib dataset, and image_02 dataset. Did I miss anything?

calib_files,image_files,detections_files_3D,detections_files_2D,detection_file_list_3D,detection_file_list_2D, this is the file I sorted

**Comment by yuanfuture** [comment]
I will revise it again according to what you said. I really appreciate your help!

**Comment by yuanfuture** [comment]
I confirmed again that the files we sorted were the same. I generated the video from the detection results and found that there seemed to be a time difference between the time when the detection box appeared and the time when the vehicle appeared in the video. For example, the detection box of frame t appeared in the video frame t+1 or even later. Do you have this condition?

**Comment by yuanfuture** [comment]
After further combing, I found the problem, but thank you for your help. Thank you very much!
