### ISSUE TITLE
OSerror

### ISSUE THREAD

**Issue by zzm-hl** [wangxiyang2022/DeepFusionMOT#2]
when I run `python main.py`, have the error `OSError: datasets/kitti/train/2D_rrc_Car_val\0000.txt not found.
`  at line 147  . 
How can I solve the problem?

**Comment by ynlx** [comment]
Hi, I have the same problem, how did you solve it?

**Comment by chisyliu** [comment]
Hello

I guess you are running the code in Ubuntu, but it seems the author ran the code in windows. Thus the folder path has some difference in ubuntu and windows

You can go to line 17 of file_operation/file.py
Change "position = detections_root + "\" + detections_file" to "position = detections_root + "/" + detections_file"
